### ISSUE TITLE
GetLogsBySinceDate test fails intermittently (Flaky test)

### ISSUE THREAD

**Issue by vijetmahabaleshwar-okta** [okta/okta-sdk-dotnet#271]
The test `Okta.Sdk.IntegrationTests.LogsScenarios.GetLogsBySinceDate` fails sometimes when run on travis as well as locally.

It seems like Okta API issue but this is blocking running ITs on travis for PRs and cron jobs. 
Error log - 
```
[xUnit.net 00:03:08.58]     Okta.Sdk.IntegrationTests.LogsScenarios.GetLogsBySinceDate [FAIL]
Failed   Okta.Sdk.IntegrationTests.LogsScenarios.GetLogsBySinceDate
Error Message:
 Okta.Sdk.OktaApiException : Sorry, there's been an error. We aren't sure what caused it, but we've logged this and will work to address it. Please try your request again. (500, E0000009)
Stack Trace:
   at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response) in /home/vagrant/okta/sdk/okta-sdk-dotnet/src/Okta.Sdk/Internal/DefaultDataStore.cs:line 158
   at Okta.Sdk.Internal.DefaultDataStore.GetArrayAsync[T](HttpRequest request, RequestContext requestContext, CancellationToken cancellationToken) in /home/vagrant/okta/sdk/okta-sdk-dotnet/src/Okta.Sdk/Internal/DefaultDataStore.cs:line 193
   at Okta.Sdk.PagedCollectionEnumerator`1.MoveNextAsync(CancellationToken cancellationToken) in /home/vagrant/okta/sdk/okta-sdk-dotnet/src/Okta.Sdk/PagedCollectionEnumerator{T}.cs:line 50
   at Okta.Sdk.Internal.CollectionAsyncEnumerator`1.MoveNext(CancellationToken cancellationToken) in /home/vagrant/okta/sdk/okta-sdk-dotnet/src/Okta.Sdk/Internal/CollectionAsyncEnumerator{T}.cs:line 61
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
   at Okta.Sdk.IntegrationTests.LogsScenarios.GetLogsBySinceDate() in /home/vagrant/okta/sdk/okta-sdk-dotnet/src/Okta.Sdk.IntegrationTests/LogsScenarios.cs:line 116
   at Okta.Sdk.IntegrationTests.LogsScenarios.GetLogsBySinceDate() in /home/vagrant/okta/sdk/okta-sdk-dotnet/src/Okta.Sdk.IntegrationTests/LogsScenarios.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by laura-rodriguez** [comment]
This issue was handled already. See [IT](https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk.IntegrationTests/LogsScenarios.cs#L45).
