### ISSUE TITLE
ListUsers() with search fails in the middle of the batch with "Invalid Search Criteria"

### ISSUE THREAD

**Issue by phi1ipp** [okta/okta-sdk-dotnet#323]
The following snippet throws an exception after producing some results
```
try
            {
                oktaClient.Users
                    .ListUsers(search: $"profile.{_attrName} pr")
                    .Select(u => u.Profile[_attrName].ToString())
                    .Distinct()
                    .ForEach(val => Console.WriteLine(string.IsNullOrEmpty(val) ? "<Empty string>" : val));
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
```

```
System.AggregateException: One or more errors occurred. (Invalid search criteria. (400, E0000031): Invalid search query.) ---> Okta.Sdk.OktaApiException: Invalid search criteria. (400, E0000031): Invalid search query.
   at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response)
   at Okta.Sdk.Internal.DefaultDataStore.GetArrayAsync[T](HttpRequest request, RequestContext requestContext, CancellationToken cancellationToken)
   at Okta.Sdk.PagedCollectionEnumerator`1.MoveNextAsync(CancellationToken cancellationToken)
   at Okta.Sdk.Internal.CollectionAsyncEnumerator`1.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.DistinctAsyncIterator`1.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.ForEachAsync_[TSource](IAsyncEnumerable`1 source, Action`2 action, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.ForEach[TSource](IAsyncEnumerable`1 source, Action`1 action, CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.ForEach[TSource](IAsyncEnumerable`1 source, Action`1 action)
   at reporting_tool.UsedAttributeValues.Run() in /Users/philippgrigoryev/projects/reporting-tool/reporting-tool/UsedAttributeValues.cs:line 31
---> (Inner Exception #0) Okta.Sdk.OktaApiException: Invalid search criteria. (400, E0000031): Invalid search query.
   at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response)
   at Okta.Sdk.Internal.DefaultDataStore.GetArrayAsync[T](HttpRequest request, RequestContext requestContext, CancellationToken cancellationToken)
   at Okta.Sdk.PagedCollectionEnumerator`1.MoveNextAsync(CancellationToken cancellationToken)
   at Okta.Sdk.Internal.CollectionAsyncEnumerator`1.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.DistinctAsyncIterator`1.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.ForEachAsync_[TSource](IAsyncEnumerable`1 source, Action`2 action, CancellationToken cancellationToken)<---

```

**Comment by phi1ipp** [comment]
It turned out that the problem is in the pagination used to iterate through the result. Here is the log of execution on a large user base...
```
... <skipped for brevity>...
HttpRequest: Uri=https://xxxxxxx.okta.com/api/v1/users?after=49800&limit=200&search=profile.SourceType+pr
HttpRequest: Uri=https://xxxxxxx.okta.com/api/v1/users?after=50000&limit=200&search=profile.SourceType+pr
System.AggregateException: One or more errors occurred. (Invalid search criteria. (400, E0000031): Invalid search query.) ---> Okta.Sdk.OktaApiException: Invalid search criteria. (400, E0000031): Invalid search query.
```

Any thoughts?

**Comment by laura-rodriguez** [comment]
Hi @phi1ipp,

Have you tried to make this request in Postman for example? 
It can help us to determine if it's an SDK or API issue/restriction.

**Comment by phi1ipp** [comment]
Hi @laura-rodriguez,

Yes, it's the same in Postman, if I submit `https://xxxxxxx.okta.com/api/v1/users?after=50000&limit=200&search=profile.SourceType+pr`

```
{
    "errorCode": "E0000031",
    "errorSummary": "Invalid search criteria.",
    "errorLink": "E0000031",
    "errorId": "oaeuSHEKjtnR3GptLF7cwdafg",
    "errorCauses": [
        {
            "errorSummary": "Invalid search query."
        }
    ]
}
```

**Comment by laura-rodriguez** [comment]
I asked the API team and they are working on a fix but it wasn't merged yet. 
As it seems you're using a custom property `sourceType` unfortunately you can't use `filter`.
You can continue using this endpoint but you can only get 50K users until the fix is pushed in.

**Comment by phi1ipp** [comment]
Thank you, @laura-rodriguez for the prompt reply. What is the best way to get notified when you push fixes into the repo and nuget package?

**Comment by laura-rodriguez** [comment]
As this is an API issue which might not require an SDK change, you'll have to keep track of the [Okta API release notes](https://developer.okta.com/docs/release-notes/) .

**Comment by phi1ipp** [comment]
Got it, thank you for the clarification!

**Comment by phi1ipp** [comment]
Hi @laura-rodriguez ,

Can you please let me know if API team has plans to fix the issue? I see the latest release doesn't have anything to address the issue.

Thank you

**Comment by laura-rodriguez** [comment]
Hi @phi1ipp ,

My team doesn't own these APIs, so we don't know much about timelines. What you can do is talk to customer support, they should give you further information about this.
