### ISSUE TITLE
Can't List Oauth Policies

### ISSUE THREAD

**Issue by mattmcnabb** [okta/okta-sdk-dotnet#331]
When I run `Client.Policies.ListPolicies(PolicyType.OauthAuthorizationPolicy).ToList()` I get the following error:

```
Okta.Sdk.OktaApiException: The request was not valid: Invalid policy type specified (400, E0000002)
at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response)
at Okta.Sdk.Internal.DefaultDataStore.GetArrayAsync[T](HttpRequest request, RequestContext requestContext, CancellationToken cancellationToken)
at Okta.Sdk.PagedCollectionEnumerator`1.MoveNextAsync(CancellationToken cancellationToken)
at Okta.Sdk.Internal.CollectionAsyncEnumerator`1.MoveNext(CancellationToken cancellationToken)
at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector,     
CancellationToken cancellationToken)
```

There doesn't appear to be a test for this scenario here:

https://github.com/okta/okta-sdk-dotnet/blob/79156f1a8652f5b4327ac0609570e9f125fc347a/src/Okta.Sdk.IntegrationTests/PoliciesScenarios.cs

Is this behavior expected? If so, how should I list Oauth policies? Thanks!

**Comment by laura-rodriguez** [comment]
Hi @mattmcnabb ,

Have you tried to make this request in Postman for example?
It can help us to determine if it's an SDK or API issue.

**Comment by laura-rodriguez** [comment]
It seems that it's not possible to make this request via Postman either. I'll inquire about this policy type, and I'll get back to you.

**Comment by laura-rodriguez** [comment]
@mattmcnabb , to list OAuth policies you have to use this endpoint instead: 
`GET /api/v1/authorizationServers/${authServerId}/policies`
https://developer.okta.com/docs/reference/api/authorization-servers/#get-all-policies

**Comment by mattmcnabb** [comment]
@laura-rodriguez Thanks, I think I understand this a little better - I need to specify an auth server to get its policies rather than query for all Oauth policies, correct?

**Comment by laura-rodriguez** [comment]
@mattmcnabb correct! if your AS is `default`, your request URI should look like this: 
```
https://{yourOktaDomain}/api/v1/authorizationServers/default/policies
```
