### ISSUE TITLE
DefaultRetryStrategy causes exception System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times

### ISSUE THREAD

**Issue by phi1ipp** [okta/okta-sdk-dotnet#335]
when building OktaClient with `DefaultRetryStragegy` with default parameters, 429 causes an exception
```
System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
   at System.Net.Http.HttpClient.CheckRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Okta.Sdk.Internal.DefaultRequestExecutor.<SendAsync>b__10_0(HttpRequestMessage x, CancellationToken y)
...
```

**Comment by phi1ipp** [comment]
Suspicion is about this fragment in DefaultRetryStrategy
```
 if (delayTimeSpan > TimeSpan.Zero)
                    {
                        await Task.Delay(delayTimeSpan, cancellationToken).ConfigureAwait(false);
                        response.Headers.TryGetValues("X-Okta-Request-Id", out var requestId);
                        AddRetryOktaHeaders(request, requestId.FirstOrDefault(), numberOfRetries);
                    }
```
so we don't actually building a new request object, but rather reusing the same `request` instance, just with updated headers

**Comment by laura-rodriguez** [comment]
Hi @phi1ipp ,

What are the steps to reproduce this issue?

**Comment by phi1ipp** [comment]
Hi @laura-rodriguez,

Here is a simple test application to run
```
        static void Main(string[] args)
        {
            var oktaClient = new OktaClient(
                new OktaClientConfiguration
                {
                    OktaDomain = "https://xxxxxx.okta.com",
                    Token = "xxxxxxxxxx",
                },
                new HttpClient(),
                null,
                new DefaultRetryStrategy(
                    OktaClientConfiguration.DefaultMaxRetries,
                    OktaClientConfiguration.DefaultRequestTimeout));

            File.ReadLines("/tmp/user-guid-list")
                .AsParallel()
                .ForAll(t =>
                {
                    var s = oktaClient.Logs
                        .GetLogs(
                            q: $"eventType eq \"user.lifecycle.create\" and target.id eq \"{t.Trim()}\"",
                            since: DateTime.Now.Add(TimeSpan.FromDays(-180d)).ToString("yyyy-MM-dd"))
                        .Select(ev => ev.Actor.AlternateId)
                        .FirstOrDefault();
                    Console.WriteLine(s.Result ?? "not found");
                });
        }
```
Put in the input file 150-200 user guid's and run it. To increase probability, you can run the second instance of the application at the same time.

Here is the full stack trace
```
 ---> System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
   at System.Net.Http.HttpClient.CheckRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Okta.Sdk.Internal.DefaultRequestExecutor.<SendAsync>b__8_0(HttpRequestMessage x, CancellationToken y) in /private/tmp/okta-sdk-dotnet/src/Okta.Sdk/Internal/DefaultRequestExecutor.cs:line 84
   at Okta.Sdk.DefaultRetryStrategy.WaitAndRetryAsync(HttpRequestMessage request, CancellationToken cancellationToken, Func`3 operation) in /private/tmp/okta-sdk-dotnet/src/Okta.Sdk/DefaultRetryStrategy.cs:line 71
   at Okta.Sdk.Internal.DefaultRequestExecutor.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /private/tmp/okta-sdk-dotnet/src/Okta.Sdk/Internal/DefaultRequestExecutor.cs:line 86
   at Okta.Sdk.Internal.DefaultDataStore.GetArrayAsync[T](HttpRequest request, RequestContext requestContext, CancellationToken cancellationToken) in /private/tmp/okta-sdk-dotnet/src/Okta.Sdk/Internal/DefaultDataStore.cs:line 193
   at Okta.Sdk.PagedCollectionEnumerator`1.MoveNextAsync(CancellationToken cancellationToken) in /private/tmp/okta-sdk-dotnet/src/Okta.Sdk/PagedCollectionEnumerator{T}.cs:line 50
   at Okta.Sdk.Internal.CollectionAsyncEnumerator`1.MoveNext(CancellationToken cancellationToken) in /private/tmp/okta-sdk-dotnet/src/Okta.Sdk/Internal/CollectionAsyncEnumerator{T}.cs:line 62
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at ConsoleApp1.Program.Main(String[] args) in /private/tmp/okta-sdk-dotnet/src/ConsoleApp1/Program.cs:line 26
```

**Comment by phi1ipp** [comment]
Hey @laura-rodriguez , 
are there any further questions I can help to clarify?

**Comment by laura-rodriguez** [comment]
Hi @phi1ipp,

I'm sorry I didn't have the time to review this yet. Is this blocking you?

**Comment by phi1ipp** [comment]
Hi @laura-rodriguez ,

Nope, don't worry. Was not sure if there is anything else I can help you with, as `question` tag was still there. I have a fix for myself, which I submitted as a PR.

**Comment by laura-rodriguez** [comment]
Thanks for the info you provided and for taking the time and submitting a PR 💯  
I need to discuss the priority with the team to see when we can work on this issue.
