### ISSUE TITLE
Exception getting thrown during high load scenarios

### ISSUE THREAD

**Issue by cwoolum** [okta/okta-sdk-dotnet#344]
When we query a large number of records, we occasionally get an exception thrown. I think the response might not have any `Content` which is causing the NullReferenceException. It would probably be good to check `response.Content != null` before performing the Concat.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Okta.Sdk.Internal.DefaultRequestExecutor.ExtractHeaders(HttpResponseMessage response)
   at Okta.Sdk.Internal.DefaultRequestExecutor.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Okta.Sdk.Internal.DefaultDataStore.GetAsync[T](HttpRequest request, RequestContext requestContext, CancellationToken cancellationToken)
   at Okta.Sdk.OktaClient.GetAsync[T](HttpRequest request, CancellationToken cancellationToken)
   at Okta.Sdk.UsersClient.GetUserAsync(String userId, CancellationToken cancellationToken)
```

**Comment by laura-rodriguez** [comment]
Hi @cwoolum,

Can you give me more details about how to reproduce this issue? What endpoint were you trying to hit?

**Comment by laura-rodriguez** [comment]
Thanks for the update @cwoolum! I'll keep this issue open to remind us that we need to take a look at this.
