### ISSUE TITLE
Exception thrown by calling GetApplicationAsync

### ISSUE THREAD

**Issue by kollerdroid** [okta/okta-sdk-dotnet#346]
When I try to get my App:

```cs
return await oktaClient.Applications.GetApplicationAsync(applicationId);
```

I get this exception:

```cs
System.InvalidOperationException: The JSON property name for 'Okta.Sdk.OpenIdConnectApplication.Credentials' collides with another property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameConflict(JsonClassInfo jsonClassInfo, JsonPropertyInfo jsonPropertyInfo)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

My app is listed - without error - by this:
```cs
return await oktaClient.Applications.ListApplications().ToList();
```

Could you help me, please?

**Comment by laura-rodriguez** [comment]
Hi @kollerdroid ,

Does this error show up only with a particular app or with all of them?

**Comment by kollerdroid** [comment]
Hi Laura,

What do you mean by "a particular app"?
I would like to list all my applications by OktaClient.

**Comment by laura-rodriguez** [comment]
So, my understanding is that when you use  `await oktaClient.Applications.ListApplications().ToList();` you get all your apps even the one that is failing when you try to retrieve it via `GetApplicationAsync`.
Have you tried to get any other applications via `GetApplicationAsync()`?  I'm assuming that you have more than one.
All of them are failing when you use this method or just one of them?

**Comment by kollerdroid** [comment]
Yes, I tried with 4 applications, the error is the same in all cases.

**Comment by laura-rodriguez** [comment]
Closing due to inactivity. Feel free to reopen if this is still happening.
