### ISSUE TITLE
OktaClientConfiguration > 'Invalid URI: The format of the URI could not be determined.'

### ISSUE THREAD

**Issue by espindl** [okta/okta-sdk-dotnet#349]
I am on a Mac. Using dotnet core (tried 3.0, 2.2 and 1.0) and VsCode. 
When I try to create OktaClientConfiguration I get: 

`System.Private.Uri.dll: 'Invalid URI: The format of the URI could not be determined.'`

On this line, no Uri nothing. There is nothing but this line in my main method.

`var conf = new OktaClientConfiguration();`

Exception has occurred: CLR/System.UriFormatException
An unhandled exception of type 'System.UriFormatException' occurred in System.Private.Uri.dll: 'Invalid URI: The format of the URI could not be determined.'
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Okta.Sdk.Internal.DefaultProxy..ctor(ProxyConfiguration proxyConfiguration, ILogger logger)
   at Okta.Sdk.Internal.DefaultHttpClient.Create(Nullable`1 connectionTimeout, ProxyConfiguration proxyConfiguration, ILogger logger)
   at Okta.Sdk.OktaClient..ctor(OktaClientConfiguration apiClientConfiguration, ILogger logger, ISerializer serializer)

**Comment by FraserHamilton** [comment]
I'm getting a very similar problem I've tried including my okta org url as an environment variable or even explicitly declaring it in the constructor and still receive this error.

**Comment by laura-rodriguez** [comment]
Hi!
Sorry for the inconvenience.

@FraserHamilton have tried this on a Mac and VS Code as well?

**Comment by laura-rodriguez** [comment]
Closing due to inactivity.

**Comment by d3m0n1n** [comment]
Hi everyone, 

Right now i have the same error, i am using 5.1.0 version of the Sdk for .NET Core 3.1, i read the docs about the ways for instanced the okta client and i tested with next examples: 

OktaDomain = "https://mydomain.oktapreview.com" 
string domain = "mydomain.oktapreview.com";
OktaDomain = $"https://{domain}"

but given me the same error, 

System.UriFormatException: Invalid URI: The format of the URI could not be determined.

also i tested validating of the URI with the next code and i had not a problem: 
var tryUri = Uri.TryCreate($"https://{_oktaConfiguration.Domain}", UriKind.RelativeOrAbsolute, out _);

so, how can i solve this case?

please help

**Comment by andriizhegurov-okta** [comment]
Hi @d3m0n1n 
Could you share your exact piece of code where you have this error?

Also if I understand your example correctly your `OktaDomain` contains URI scheme already and you're adding another `https://` to this string. In this case result will be something like `https://https://mydomain.oktapreview.com` which is not a valid URI string.

**Comment by d3m0n1n** [comment]
Hello again, @andriizhegurov-okta 

OK, as background, i  trying to connect with the sdk, but it keeps giving format error in the uri, the error is the folllowing:

![image](https://user-images.githubusercontent.com/13068495/129623867-419fdae0-29fd-4f3d-844e-11941c8cd8b0.png)

the code that i use for connect me in OKTA:

```csharp
            var jwk = new JsonWebKeyConfiguration(oktaConfig.PrivateKey);

            var scopes = oktaConfig.Scopes.Split(':');
            
            var config = new OktaClientConfiguration()
            {
                OktaDomain = $"https://{oktaConfig.Domain}",
                AuthorizationMode = AuthorizationMode.PrivateKey,
                Scopes = scopes.ToList(),
                PrivateKey = jwk,
                ClientId = oktaConfig.ClientId
            };

            var client = new OktaClient(config);
```

if I remove the https format in OktaDomain, it asks me to add the format with https in a exception, something like that:

![image](https://user-images.githubusercontent.com/13068495/129625146-28016638-5ce8-4ca5-9bee-3b5290b11178.png)

the code that i use in this case:

```csharp

            var jwk = new JsonWebKeyConfiguration(oktaConfig.PrivateKey);

            var scopes = oktaConfig.Scopes.Split(':');
            
            var config = new OktaClientConfiguration()
            {
                OktaDomain = oktaConfig.Domain,
                AuthorizationMode = AuthorizationMode.PrivateKey,
                Scopes = scopes.ToList(),
                PrivateKey = jwk,
                ClientId = oktaConfig.ClientId
            };

            var client = new OktaClient(config);
            
            return client; 

```


the case is that, i use MacOs with Rider and the same code in Windows with Visual Studio it works fine, but in my laptop not work. so, i don't know what happing.

I need your help.

**Comment by andriizhegurov-okta** [comment]
@d3m0n1n we were unable to reproduce the issue with the code above using MacOs and Rider.
Can you probably give us a link to GitHub repo with complete application with minimal code needed for reproduction without any sensitive data? 

Alternatively you can try debugging your App using source code of the OktaSDK package to find the error cause yourself. To do this, fetch this repo and add it as a project reference to your project instead of NuGet package reference.

**Comment by d3m0n1n** [comment]
Finally i found the fix. 

The Okta Client class needs of HttpClient instance for work and you must pass it in a constructor parameter, this way i fixed.

```csharp

            var jwk = new JsonWebKeyConfiguration(oktaConfig.PrivateKey);

            var scopes = oktaConfig.Scopes.Split(':');
            
            var client = new OktaClient(new OktaClientConfiguration()
            {
                OktaDomain = $"https://{oktaConfig.Domain}",
                AuthorizationMode = AuthorizationMode.PrivateKey,
                Scopes = scopes.ToList(),
                PrivateKey = jwk,
                ClientId = oktaConfig.ClientId
            }, _httpClient);

```


thank you very much for you time.
