### ISSUE TITLE
Initialise Okta client with token throws exception "Method not found: ‘System.Collections.Generic.IDictionary`2<YamlDotNet.RepresentationModel.YamlNode,YamlDotNet.RepresentationModel.YamlNode>"

### ISSUE THREAD

**Issue by AashiqDurga** [okta/okta-sdk-dotnet#467]
## Current behavior

I try to create a new instance of the Okta client with the domain and token in the configuration.  But I keep getting the exception below 

I new up the client like below

var client = new OktaClient(new OktaClientConfiguration{
OktaDomain = “https://{mydomain}”,
Token = “my token” // this is a valid token as I can use it in postman
});

I even tried with a clientId and setting the authMode.SSWS but get the following exeception.

System.MissingMethodException: Method not found: ‘System.Collections.Generic.IDictionary`2<YamlDotNet.RepresentationModel.YamlNode,YamlDotNet.RepresentationModel.YamlNode> YamlDotNet.RepresentationModel.YamlMappingNode.get_Children()’.
at FlexibleConfiguration.Providers.YamlVisitors.YamlVisitorBase.VisitChildren(YamlMappingNode mapping)
at FlexibleConfiguration.Providers.YamlVisitors.ContextAwareMappingVisitor.Visit(YamlMappingNode mapping)
at FlexibleConfiguration.Providers.YamlVisitors.YamlVisitorBase.YamlDotNet.RepresentationModel.IYamlVisitor.Visit(YamlMappingNode mapping)
at YamlDotNet.RepresentationModel.YamlMappingNode.Accept(IYamlVisitor visitor)
at FlexibleConfiguration.Providers.YamlVisitors.ContextAwareVisitor.Visit(YamlMappingNode mapping)
at FlexibleConfiguration.Providers.YamlVisitors.YamlVisitorBase.YamlDotNet.RepresentationModel.IYamlVisitor.Visit(YamlMappingNode mapping)
at YamlDotNet.RepresentationModel.YamlMappingNode.Accept(IYamlVisitor visitor)
at FlexibleConfiguration.Providers.YamlVisitors.YamlVisitorBase.VisitChildren(YamlDocument document)
at FlexibleConfiguration.Providers.YamlVisitors.YamlVisitorBase.Visit(YamlDocument document)
at FlexibleConfiguration.Providers.YamlVisitors.YamlVisitorBase.YamlDotNet.RepresentationModel.IYamlVisitor.Visit(YamlDocument document)
at YamlDotNet.RepresentationModel.YamlDocument.Accept(IYamlVisitor visitor)
at FlexibleConfiguration.Providers.YamlVisitors.YamlVisitorBase.VisitChildren(YamlStream stream)
at FlexibleConfiguration.Providers.YamlVisitors.YamlVisitorBase.Visit(YamlStream stream)
at FlexibleConfiguration.Providers.YamlVisitors.YamlVisitorBase.YamlDotNet.RepresentationModel.IYamlVisitor.Visit(YamlStream stream)
at YamlDotNet.RepresentationModel.YamlStream.Accept(IYamlVisitor visitor)
at FlexibleConfiguration.Providers.YamlParser.Parse(Stream input)
at FlexibleConfiguration.Providers.YamlProvider.Load()
at FlexibleConfiguration.ConfigurationBuilder.Add(IConfigurationProvider provider)
at FlexibleConfiguration.ConfigurationBuilderProviderExtensions.AddJson(IConfigurationBuilder builder, String json, String root, ILogger logger)
at FlexibleConfiguration.ConfigurationBuilderProviderExtensions.AddJsonFile(IConfigurationBuilder builder, String filePath, Boolean optional, String root, ILogger logger)
at Okta.Sdk.OktaClient.GetConfigurationOrDefault(OktaClientConfiguration apiClientConfiguration)
at Okta.Sdk.OktaClient…ctor(OktaClientConfiguration apiClientConfiguration, ILogger logger, ISerializer serializer)

I have also tried options 2 and 3 pointed out here https://github.com/okta/okta-sdk-dotnet#configuration-reference with not luck and the  same exception.
## Expected behavior

A new client to be available so I can manage users programmatically.
## Minimal reproduction of the problem with instructions

var client = new OktaClient(new OktaClientConfiguration{
OktaDomain = “https://{mydomain}”,
Token = “my token” // this is a valid token as I can use it in postman
});

## Environment

- OS: MacOs Catalina 10.15.7
- Browser: 

- .Net Framework: .Net Core 3.1

- Other:

**Comment by AashiqDurga** [comment]
Found that YamlDotNet nuget package was being used in a total different resource to deserialize a request but was some how messing with a totally different REST resource I was using.

removed the package and depricated the unused endpoint. all working now

**Comment by laura-rodriguez** [comment]
Glad you got it working ⭐ !

**Comment by Rajesh35hsp** [comment]
deleted the temp folder in C:\Users\myname\AppData\Local\Temp and it started working.
Weird!!!
