### ISSUE TITLE
IDX11025: Cannot serialize object of type: 'Microsoft.IdentityModel.Tokens.JsonWebKey' into property: 'jwk'

### ISSUE THREAD

**Issue by pbacka** [okta/okta-sdk-dotnet#730]
### Describe the bug?

getting exception in ListUsers

```
var privateKey = new JsonWebKeyConfiguration
{
	D = {D},
	P = {P},
	Q = {Q},
	Dp = {Dp},
	Dq = {Dq},
	Qi = {Qi},
	Kty = "RSA",
	E = {E},
	N = {N}
};

var userApi = new UserApi(
	new Configuration
	{
		OktaDomain = "https://" + oktaTenant.Domain,
		AuthorizationMode = AuthorizationMode.PrivateKey,
		ClientId = oktaTenant.ClientId,
		Scopes = new HashSet<string> { "okta.users.read" },
		PrivateKey = privateKey
	}
);

userApi.ListUsers(limit: maxUsers, search: search);
```

### What is expected to happen?

should return user objects

### What is the actual behavior?

throws System.InvalidOperationException: Something went wrong when creating the signed JWT. Verify your private key.

### Reproduction Steps?

run the code pasted below

### .NET Version

6.0.424

### SDK Version

8.0.1

### OS version

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by pbacka** [comment]
Exception detail

```
An exception has occurred with the following error message: "Something went wrong when creating the signed JWT. Verify your private key."
System.InvalidOperationException: Something went wrong when creating the signed JWT. Verify your private key.
 ---> System.ArgumentException: IDX11025: Cannot serialize object of type: 'Microsoft.IdentityModel.Tokens.JsonWebKey' into property: 'jwk'.
   at Microsoft.IdentityModel.Tokens.Json.JsonSerializerPrimitives.WriteObject(Utf8JsonWriter& writer, String key, Object obj)
   at Microsoft.IdentityModel.Tokens.Json.JsonSerializerPrimitives.WriteObjects(Utf8JsonWriter& writer, IDictionary`2 dictionary)
   at System.IdentityModel.Tokens.Jwt.JwtHeader.SerializeToJson()
   at System.IdentityModel.Tokens.Jwt.JwtHeader.Base64UrlEncode()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
   at Okta.Sdk.Client.DefaultDpopProofJwtGenerator.GenerateJwt(String nonce, String httpMethod, String uri, String accessToken)
   --- End of inner exception stack trace ---
   at Okta.Sdk.Client.DefaultDpopProofJwtGenerator.GenerateJwt(String nonce, String httpMethod, String uri, String accessToken)
   at Okta.Sdk.Api.OAuthApi.GetBearerTokenWithHttpInfoAsync(CancellationToken cancellationToken)
   at Okta.Sdk.Api.OAuthApi.GetBearerTokenAsync(CancellationToken cancellationToken)
   at Okta.Sdk.Client.DefaultOAuthTokenProvider.RequestAccessTokenAsync(CancellationToken cancellationToken)
   at Okta.Sdk.Client.DefaultOAuthTokenProvider.GetAccessTokenResponseAsync(Boolean forceRenew, CancellationToken cancellationToken)
   at Okta.Sdk.Client.DefaultOAuthTokenProvider.AddOrUpdateAuthorizationHeader(RequestOptions requestOptions, String requestUri, String httpMethod, CancellationToken cancellationToken)
   at Okta.Sdk.Client.OktaPagedCollectionEnumerator`1.MoveNextAsync()
   at Okta.Sdk.Client.OktaCollectionAsyncEnumerator`1.MoveNextAsync()
   at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerableHelpers.cs:line 49
   at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerableHelpers.cs:line 91
   at System.Linq.OrderedAsyncEnumerable`1.ToListAsync(CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/OrderedAsyncEnumerable.cs:line 156
```

**Comment by laura-rodriguez** [comment]
Hi @pbacka,

Thanks for reporting this issue. Looking at your stack trace, it seems there's a problem with the DPoP JWT generation. Since we may need to dig further into your org configuration, please contact the Okta Customer Support Team at developers@okta.com so we can work with them to fix the issue.

**Comment by bryanapellanes-okta** [comment]
Closing due to lack of activity.  Feel free to reopen if this is still an issue.
